services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hashids\Hashids:
    arguments:
      - '%hashids.salt%'
      - '%hashids.min_hash_length%'
      - '%hashids.alphabet%'

  GalDigitalGmbh\HashidsBundle\Service\:
    resource: '../../Service'

  GalDigitalGmbh\HashidsBundle\Twig\:
    resource: '../../Twig'
    tags: [twig.extension]
